In [3]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_excel('C:/Users/shah1/Downloads/Netflix Dummy Data/Netflix Dummy Data/Netflix_Unclean_Project.xlsx')

In [5]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,CUST10927,Customer 927,25,Bridgerton,TV Show,Drama,Japan,Premium,Gaming Console,PayPal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,CUST10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,PayPal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,CUST10683,Customer 683,40,Money Heist,TV Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,CUST10515,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,CUST10366,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20

In [6]:
df.tail()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
1008,CUST55545,Customer 515,44,You,TV Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
1009,CUST55546,Customer 366,57,The Witcher,TV Show,Comedy,Canada,Premium,Smart TV,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20
1010,CUST55547,Customer 656,42,You,Movie,NaN,Germany,Basic,Mobile,Credit Card,Paused,2023-10-31,2025-08-10,43.5,149,32,11,4.5,12,7
1011,CUST55548,Customer 657,22,Squid Game,TV Show,Documentary,Canada,Premium,Smart TV,Credit Card,Active,2025-05-15,2025-09-11,42.3,649,19,11,2.8,12,23
1012,CUST55549,Customer 530,61,Elite,Movie,Drama,Germany,Standard,Tablet,Debit Card,Paused,2025-04-08,2026-05-21,19.4,499,14,91,3.5,15,23

In [7]:
# inital data exploration
df.shape

(1013, 20)

In [8]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Title', 'Content_Type', 'Genre',
       'Country', 'Subscription_Plan', 'Device', 'Payment_Method',
       'Account_Status', 'Join_Date', 'Last_Watch_Date', 'Watch_Hours',
       'Monthly_Fee', 'Movies_Watched', 'Episodes_Watched', 'Avg_Rating',
       'Monthly_Sessions', 'Download_Count'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1013 entries, 0 to 1012
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        1013 non-null   object
 1   Customer_Name      1013 non-null   object
 2   Age                1013 non-null   int64
 3   Title              1013 non-null   object
 4   Content_Type       1013 non-null   object
 5   Genre              1010 non-null   object
 6   Country            1013 non-null   object
 7   Subscription_Plan  1013 non-null   object
 8   Device             1009 non-null   object
 9   Payment_Method     1008 non-null   object
 10  Account_Status     1013 non-null   object
 11  Join_Date          1013 non-null   datetime64[ns]
 12  Last_Watch_Date    1013 non-null   datetime64[ns]
 13  Watch_Hours        1013 non-null   float64
 14  Monthly_Fee        1013 non-null   int64
 15  Movies_Watched     1013 non-null   int64
 16  Episodes_Watched   1013 non-null   int64
 17  Avg_Rating         1013 non-null   float64
 18  Monthly_Sessions   1013 non-null   int64
 19  Download_Count     1013 non-null   int64
dtypes: datetime64[ns](2), float64(2), int64(6), object(10)
memory usage: 158.4+ KB

In [10]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors = 'coerce')
df['Last_Watch_Date'] = pd.to_datetime(df['Last_Watch_Date'], errors = 'coerce')

In [11]:
df.describe()

,Age,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1013.000000,1013,1013,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000,1013.000000
mean,42.063179,2023-12-16 10:21:12.260612096,2024-11-27 19:59:45.784797696,42.417473,436.222113,18.187562,59.834156,3.752419,16.686081,12.472853
min,-10.000000,2022-01-01 00:00:00,2022-01-21 00:00:00,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,2022-12-08 00:00:00,2023-12-26 00:00:00,25.700000,149.000000,9.000000,31.000000,3.100000,10.000000,6.000000
50%,43.000000,2023-12-29 00:00:00,2024-12-03 00:00:00,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.000000,2024-12-13 00:00:00,2025-11-14 00:00:00,58.100000,649.000000,27.000000,91.000000,4.400000,24.000000,19.000000
max,200.000000,2025-11-01 00:00:00,2027-08-18 00:00:00,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000
std,15.245811,NaN,NaN,23.988529,214.348252,10.123758,34.895300,0.722812,8.290083,7.577303

In [12]:
# Missing Values in data
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                3
Country              0
Subscription_Plan    0
Device               4
Payment_Method       5
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [13]:
# Duplicate Records

df.duplicated().sum()

np.int64(5)

In [14]:
#  Removing duplicates , inplace makes sure it get rmeoved from og data
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
# Dirty Values - N/A, NULL , Blank , Spaces
df.replace(
    ['N/A','NULL','',' '],np.nan,inplace = True
)

In [17]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                4
Country              1
Subscription_Plan    0
Device               4
Payment_Method       7
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [18]:
# Extra Spaces Remvoing
df = df.apply(lambda x : x.str.strip() if x.dtype == 'object' else x)

In [19]:
#Standardize Text
#  Data can in upper /lower/mix in nay format so have to standardize it propely.

df = df.apply(lambda x: x.astype(str).str.strip().str.title() if x.dtype == 'object' else x)

In [20]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,Account_Status,Join_Date,Last_Watch_Date,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
0,Cust10927,Customer 927,25,Bridgerton,Tv Show,Drama,Japan,Premium,Gaming Console,Paypal,Active,2024-06-20,2024-12-21,28.0,649,5,97,3.6,11,3
1,Cust10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,Active,2024-01-01,2024-08-14,0.0,149,5,84,4.5,22,19
2,Cust10683,Customer 683,40,Money Heist,Tv Show,Sci-Fi,France,Basic,Tablet,Debit Card,Paused,2024-11-18,2025-10-31,28.9,149,16,106,3.8,26,3
3,Cust10515,Customer 515,44,You,Tv Show,Action,Spain,Premium,Gaming Console,Credit Card,Active,2023-02-21,2023-06-18,27.6,649,10,24,2.6,27,9
4,Cust10366,Customer 366,57,The Witcher,Tv Show,Comedy,Canada,Premium,Smart Tv,Credit Card,Active,2024-01-16,2025-06-09,32.0,649,10,78,3.2,15,20

In [21]:
#  make varible of all numeric columns

numeric_columns = ['Age', 'Watch_Hours', 'Monthly_Fee', 'Movies_Watched',
                   'Episodes_Watched','Avg_Rating', 'Monthly_Sessions',
                   'Download_Count']

In [22]:
# This will makse sure all numeric columns are numeric and erroe will marked as nan
for column in numeric_columns :
  df[column] = pd.to_numeric(df[column],errors = 'coerce')

In [23]:
df.describe(include = 'number')

,Age,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000
mean,42.097222,42.449107,435.960317,18.226190,59.766865,3.751984,16.690476,12.448413
std,15.258334,24.016448,214.461100,10.099231,34.916046,0.724172,8.287380,7.559714
min,-10.000000,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,25.650000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,54.000000,58.100000,649.000000,27.000000,90.250000,4.400000,24.000000,19.000000
max,200.000000,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000

In [24]:
# here above we can see that column age have negavtive in min and 200 somehting in max which is wrong so do this set a limit
df = df[(df['Age']>= 1)& (df['Age']<=100)]

In [25]:
df.describe(include = 'number')

,Age,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count
count,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000
mean,41.973081,42.391326,436.543370,18.242273,59.723829,3.751346,16.673978,12.449651
std,13.811906,24.016402,214.305681,10.092691,34.891084,0.723284,8.285836,7.559756
min,18.000000,-20.000000,-649.000000,1.000000,0.000000,2.500000,2.000000,0.000000
25%,30.000000,25.450000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000
50%,43.000000,42.300000,499.000000,18.000000,59.000000,3.700000,17.000000,12.000000
75%,53.500000,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000
max,65.000000,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000

In [26]:
#  Negative  Values
df = df[df['Watch_Hours']>= 0]
df = df[df['Monthly_Fee']>=0]

In [27]:
df.isnull().sum()

Customer_ID          0
Customer_Name        0
Age                  0
Title                0
Content_Type         0
Genre                0
Country              0
Subscription_Plan    0
Device               0
Payment_Method       0
Account_Status       0
Join_Date            0
Last_Watch_Date      0
Watch_Hours          0
Monthly_Fee          0
Movies_Watched       0
Episodes_Watched     0
Avg_Rating           0
Monthly_Sessions     0
Download_Count       0
dtype: int64

In [28]:
#  here we doing customer_revenue cause it will help us see wht revenue we got from user
#  It tells customer wise how much revenue generated
df['Customer_Revenue'] = df['Monthly_Fee'] * df['Monthly_Sessions']

In [29]:
# Enagment Score
#  iT help us understand how much customer engament is with our content

df['Engagement_Score'] = df ['Watch_Hours']+ df ['Monthly_Sessions'] + df['Download_Count']

In [30]:
# Watch Category - low/medium.high
#  how much time customer spends wathving content
# HAve make bins means basket in whihc we will divide our Customer
# HAve give labels for each basket

bins = [0, 20, 50,100,  np.inf ]
labels = ['Low', 'Medium', 'High', 'Very-High']

df['Watch_Category'] = pd.cut(df['Watch_Hours'],bins = bins ,labels = labels, include_lowest= True)

In [31]:
print(df.columns.tolist())

['Customer_ID', 'Customer_Name', 'Age', 'Title', 'Content_Type', 'Genre', 'Country', 'Subscription_Plan', 'Device', 'Payment_Method', 'Account_Status', 'Join_Date', 'Last_Watch_Date', 'Watch_Hours', 'Monthly_Fee', 'Movies_Watched', 'Episodes_Watched', 'Avg_Rating', 'Monthly_Sessions', 'Download_Count', 'Customer_Revenue', 'Engagement_Score', 'Watch_Category']

In [32]:
 #  Customer Age Group
 # This will tells us which age  are our max users.

bins = [0, 10 , 20 , 30, 40, 50 , 100]
labels = ['1-10', '11-20', '21-30', '31-40', '41-50', '51+']

df['Age_Group'] = pd.cut(df['Age'], bins = bins , labels = labels , include_lowest = True)

In [33]:
df['Age_Group'].value_counts()

Age_Group
51+      325
41-50    211
21-30    208
31-40    189
11-20     62
1-10       0
Name: count, dtype: int64

In [34]:
#  Account_Status_Flag
# Account whihc are active and non active

df['Active_Flag'] = np.where (df['Account_Status'] == 'Active', 1,0)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 995 entries, 0 to 1012
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        995 non-null    object
 1   Customer_Name      995 non-null    object
 2   Age                995 non-null    int64
 3   Title              995 non-null    object
 4   Content_Type       995 non-null    object
 5   Genre              995 non-null    object
 6   Country            995 non-null    object
 7   Subscription_Plan  995 non-null    object
 8   Device             995 non-null    object
 9   Payment_Method     995 non-null    object
 10  Account_Status     995 non-null    object
 11  Join_Date          995 non-null    datetime64[ns]
 12  Last_Watch_Date    995 non-null    datetime64[ns]
 13  Watch_Hours        995 non-null    float64
 14  Monthly_Fee        995 non-null    int64
 15  Movies_Watched     995 non-null    int64
 16  Episodes_Watched   995 non-null    int64
 17  Avg_Rating         995 non-null    float64
 18  Monthly_Sessions   995 non-null    int64
 19  Download_Count     995 non-null    int64
 20  Customer_Revenue   995 non-null    int64
 21  Engagement_Score   995 non-null    float64
 22  Watch_Category     995 non-null    category
 23  Age_Group          995 non-null    category
 24  Active_Flag        995 non-null    int64
dtypes: category(2), datetime64[ns](2), float64(3), int64(8), object(10)
memory usage: 188.9+ KB

In [36]:
df.describe(include = 'number')

,Age,Watch_Hours,Monthly_Fee,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Active_Flag
count,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000,995.000000
mean,41.920603,42.605126,438.396985,18.217085,59.514573,3.754573,16.701508,12.460302,7339.680402,71.766935,0.708543
std,13.797644,23.784772,209.136478,10.085605,34.855299,0.723983,8.280686,7.564557,5344.095657,26.202570,0.454662
min,18.000000,0.000000,149.000000,1.000000,0.000000,2.500000,2.000000,0.000000,298.000000,11.000000,0.000000
25%,30.000000,25.700000,149.000000,9.000000,30.000000,3.100000,10.000000,6.000000,2682.000000,51.200000,0.000000
50%,43.000000,42.300000,499.000000,18.000000,58.000000,3.700000,17.000000,12.000000,5841.000000,71.700000,1.000000
75%,53.000000,58.100000,649.000000,27.000000,90.000000,4.400000,24.000000,19.000000,11477.000000,90.050000,1.000000
max,65.000000,138.300000,649.000000,35.000000,120.000000,5.000000,30.000000,25.000000,19470.000000,167.300000,1.000000

In [37]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:1534@localhost/Netflix_db')

In [38]:
df.to_sql(
    'netflix_users',
    con = engine,
    if_exists = 'replace', 
    index = False
)

995

In [39]:
df.head()

,Customer_ID,Customer_Name,Age,Title,Content_Type,Genre,Country,Subscription_Plan,Device,Payment_Method,...,Movies_Watched,Episodes_Watched,Avg_Rating,Monthly_Sessions,Download_Count,Customer_Revenue,Engagement_Score,Watch_Category,Age_Group,Active_Flag
0,Cust10927,Customer 927,25,Bridgerton,Tv Show,Drama,Japan,Premium,Gaming Console,Paypal,...,5,97,3.6,11,3,7139,42.0,Medium,21-30,1
1,Cust10631,Customer 631,38,Bridgerton,Movie,Documentary,Japan,Basic,Mobile,Paypal,...,5,84,4.5,22,19,3278,41.0,Low,31-40,1
2,Cust10683,Customer 683,40,Money Heist,Tv Show,Sci-Fi,France,Basic,Tablet,Debit Card,...,16,106,3.8,26,3,3874,57.9,Medium,31-40,0
3,Cust10515,Customer 515,44,You,Tv Show,Action,Spain,Premium,Gaming Console,Credit Card,...,10,24,2.6,27,9,17523,63.6,Medium,41-50,1
4,Cust10366,Customer 366,57,The Witcher,Tv Show,Comedy,Canada,Premium,Smart Tv,Credit Card,...,10,78,3.2,15,20,9735,67.0,Medium,51+,1